[project]
name = "carbon-footprint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "gradio>=5.46.0",
    "pycatia>=0.9.1",
]
